- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/nginx.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/php-fpm.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/git.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/composer.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/adminer.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/uniman.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/phpinfo.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/phpunit.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/visualphpunit.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/graphviz.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/redis.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/sami.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/yarn.git
- src: git+http://192.168.202.101/git/sportisimo/ansible/roles/gulp.git
- src: AbdoulNdiaye.Blackfire
- src: geerlingguy.nodejs
#- src: geerlingguy.java
#- src: geerlingguy.elasticsearch
#- src: crowdskout.elasticsearch-cerebro